
export enum AlarmType {
  HIGH_PRESSURE = "HIGH_PRESSURE",
  LOW_PRESSURE = "LOW_PRESSURE",
  HIGH_TEMPERATURE = "HIGH_TEMPERATURE",
  LOW_TEMPERATURE = "LOW_TEMPERATURE",
  LOGIN_FAILED = "LOGIN_FAILED",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  ERROR = "ERROR",
}
