spring:
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/smart-home
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: milicftn@gmail.com
    password: zpfomujclzozrrnr
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
custom:
  jwtSecret: superepiksecret
  clientUrl: https://localhost:4200
  authTokenExpirationMilliseconds: 2592000000
  jwtActivateEmailTokenExpiration: 86400000
  jwtForgotPasswordExpiration: 3600000
  createUserTokenExpirationMilliseconds: 2592000000
  messageSource: messages
  defaultLocale: en
  senderEmail: taxify@gmail.com
server:
  servlet:
    contextPath: /api
  port: '8081'
  ssl:
    key-store: src/main/resources/keystore/keystore.jks
    key-store-password: Micomilic123!
    key-password: Micomilic123!
    enabled: true
    key-alias: root
